# -*- coding: utf-8 -*-
"""Generates docs/ACCURACY.md: the per-gate accuracy record measured on the public
corpus (0.8, external review: a single accuracy number is meaningless; per-gate TP/FP/FN
on a reproducible corpus is the honest form).

Every number here is re-derivable by anyone: `python corpus/run_corpus.py` runs the
same decks through the CLI, and CI keeps the table true (the corpus job fails on drift).

Usage: python scripts/make_accuracy_table.py   (re-runs the corpus, rewrites the doc)
"""
import glob
import io
import json
import os
import subprocess
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORPUS = os.path.join(ROOT, "corpus")
OUT = os.path.join(ROOT, "docs", "ACCURACY.md")


def _cli(args):
    env = dict(os.environ)
    env["ARCHFORGE_LANG"] = "en"
    env["PYTHONPATH"] = os.path.join(ROOT, "src") + os.pathsep + env.get("PYTHONPATH", "")
    return subprocess.run([sys.executable, "-m", "archforge"] + args,
                          capture_output=True, text=True, encoding="utf-8", env=env,
                          stdin=subprocess.DEVNULL)


def main():
    tp = Counter()          # expected and found
    fp = Counter()          # found but not expected
    fn = Counter()          # expected but not found
    tn_decks = defaultdict(int)   # decks where the code was absent and correctly silent
    generators = set()
    per_deck = []           # (want, got) pairs; TN needs the full code set, so two passes
    n_negative = 0
    for mpath in sorted(glob.glob(os.path.join(CORPUS, "*", "*.json"))):
        with io.open(mpath, encoding="utf-8") as f:
            m = json.load(f)
        if m.get("expect_exit2"):
            continue   # controlled-error fixtures are covered by the runner, not the table
        deck = os.path.splitext(mpath)[0] + ".pptx"
        if not os.path.exists(deck):
            continue
        generators.add(m.get("generator", "?").split(" ")[0])
        want = Counter({k: int(v) for k, v in m.get("expected", {}).items()})
        if not want:
            n_negative += 1
        r = _cli([deck, "--profile", m.get("profile", "full"), "--json"])
        doc = json.loads(r.stdout)
        got = Counter(f["code"] for f in doc.get("errors", []) + doc.get("warnings", [])
                      if f["code"] != "W18")
        per_deck.append((want, got))
        for code in set(want) | set(got):
            w, g = want[code], got[code]
            tp[code] += min(w, g)
            fp[code] += max(0, g - w)
            fn[code] += max(0, w - g)
    n_decks = len(per_deck)
    # second pass: a code counts as a deck-level true negative when neither expected nor
    # observed on that deck (order-independent: the code universe is complete here)
    universe = set(list(tp) + list(fp) + list(fn))
    for want, got in per_deck:
        present = set(want) | set(got)
        for code in universe - present:
            tn_decks[code] += 1

    codes = sorted(set(list(tp) + list(fp) + list(fn)),
                   key=lambda c: (c[0] != "E", int(c[1:])))
    lines = [
        "# Accuracy record (public corpus)",
        "",
        "Per-gate counts measured on the [public corpus](../corpus/), regenerated by",
        "`python scripts/make_accuracy_table.py`. Every number is third-party",
        "reproducible: the same decks and manifests ship in this repository, and CI",
        "fails on any drift.",
        "",
        "Honest scope: this corpus is a seed (%d decks from %d generator families,"
        % (n_decks, len(generators)),
        "%d of them clean negatives). It proves the gates fire on constructed ground"
        % n_negative,
        "truth and stay silent on clean decks; it is not yet a field-scale benchmark.",
        "Growing it (Google Slides / Canva / LibreOffice exports, multi-master corporate",
        "templates, contributed false positives) is the highest-value contribution this",
        "project takes; see [corpus/README.md](../corpus/README.md).",
        "",
        "| Gate | TP | FP | FN | Deck-level TN | Precision | Recall |",
        "|:----:|---:|---:|---:|---:|---:|---:|",
    ]
    for c in codes:
        p = tp[c] / (tp[c] + fp[c]) if (tp[c] + fp[c]) else float("nan")
        r_ = tp[c] / (tp[c] + fn[c]) if (tp[c] + fn[c]) else float("nan")
        lines.append("| %s | %d | %d | %d | %d | %.2f | %.2f |"
                     % (c, tp[c], fp[c], fn[c], tn_decks[c], p, r_))
    lines += [
        "",
        "Gates absent from the table have no positive fixture in the corpus yet",
        "(their behavior is covered by the unit/property suites, not by corpus ground",
        "truth). W18 is excluded by design: it is an abstention signal, not a finding.",
        "",
    ]
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", OUT, "(%d gates, %d decks)" % (len(codes), n_decks))
    if sum(fp.values()) or sum(fn.values()):
        print("WARNING: corpus has FP/FN; the corpus runner should be failing")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
